USE master;
GO

CREATE DATABASE DapperStudy;
GO

USE DapperStudy;
GO

IF OBJECT_ID('TB_ORDER_DETAIL') IS NOT NULL
	DROP TABLE TB_ORDER_DETAIL

IF OBJECT_ID('TB_ORDER') IS NOT NULL
	DROP TABLE TB_ORDER

IF OBJECT_ID('TB_PRODUCT') IS NOT NULL
	DROP TABLE TB_PRODUCT

CREATE TABLE TB_PRODUCT(
	[COD_PRODUCT] [int] IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[TXT_DESCRIPTION] [varchar](100) NOT NULL,
    [VAL_PRICE] decimal(10,2) NOT NULL
)

CREATE TABLE TB_ORDER(
     [COD_ORDER] [int] IDENTITY(1,1) PRIMARY KEY NOT NULL,
     [DAT_ORDER] [datetime] NOT NULL DEFAULT GETDATE()
)

CREATE TABLE TB_ORDER_DETAIL(
	[COD_ORDER_DETAIL] [int] IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[COD_ORDER] [int] NOT NULL,
	[COD_PRODUCT] [int] NOT NULL,
	[QTD_PRODUCT] [int] NOT NULL,
	CONSTRAINT FK_TB_PRODUCT FOREIGN KEY (COD_PRODUCT) REFERENCES TB_PRODUCT(COD_PRODUCT),
    CONSTRAINT FK_TB_ORDER FOREIGN KEY(COD_ORDER) REFERENCES TB_ORDER(COD_ORDER)
)


INSERT INTO TB_PRODUCT (TXT_DESCRIPTION,VAL_PRICE) VALUES ('PRODUCT 1',1.1),('PRODUCT 2',1.2),('PRODUCT 3',1.7)

DECLARE @ORDERID int
INSERT INTO TB_ORDER (DAT_ORDER)
VALUES (GETDATE())
SET @ORDERID = SCOPE_IDENTITY()
INSERT INTO TB_ORDER_DETAIL (COD_ORDER,COD_PRODUCT,QTD_PRODUCT)
VALUES (@ORDERID, 1,2),(@ORDERID,2,3), (@ORDERID,3,1)


SELECT * 
FROM TB_ORDER o 
        INNER JOIN TB_ORDER_DETAIL od 
           ON o.COD_ORDER = od.COD_ORDER
        INNER JOIN TB_PRODUCT p
           ON p.COD_PRODUCT = od.COD_PRODUCT

